电商项目/Lang/Lang/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lang/',include('myapp.urls',namespace='lang'))
]

电商项目/Lang/myapp/urls.py
from django.contrib import admin
from django.conf.urls import url

from . import views

app_name='myapp'

urlpatterns = [
    url('^index/', views.index ,name='index'),
    # 四个基础的展示页
    url('^home/', views.home, name='home'),
    url('^market/', views.market, name='market'),
    url('^cart/', views.cart, name='cart'),
    url('^mine/', views.mine, name='mine'),

    # 对右侧数据通过标签页进行更改
    url('^changeMenu/(?P<typeid>\d+)/', views.changeMenu,name='changeMenu'),

    # 登陆注册页面
    url('^register/', views.register, name='register'),
    url('^login/', views.login, name='login'),

    # 注册信息进行判断
    url('^judge_name/', views.judge_name, name='judge_name'),
    url('^judge_email/', views.judge_email, name='judge_email'),

    # 对登录信息进行判断
    url('^judge_login/', views.judge_login, name='judge_login'),

    # mine中进行退出
    url('^sign_out/', views.sign_out, name='sign_out'),

    # 搜索物品
    url('^search/', views.search, name='search'),

    # 将market中的物品添加到购物车和减操作
    url('^add_to_cart/', views.add_to_cart, name='add_to_cart'),
    url('^sub_from_cart/', views.sub_from_cart, name='sub_from_cart'),

    # 对小球进行判断

    url('^judge_ball/', views.judge_ball, name='judge_ball'),

    # 点击下单按钮进行下单
    url('^place_an_order/', views.place_an_order, name='place_an_order'),

    # 进行订单商品的展示
    url('^show_order/', views.show_order, name='show_order'),

]

电商项目/Lang/templates/user/login.html
{% extends 'base.html' %}
{% load static %}


{% block ext_css %}
    <link rel="stylesheet" href="{% static 'lang/register_login/css/login.css' %}">
{% endblock %}

{% block content %}

    <div class="box">

        {#        注册头部#}

        <div class="login_register" style="line-height: 2rem">
            <span style="font-size: larger;float: right">
                <a class="btn btn-default" href="{% url 'lang:register' %}" role="button">&nbsp;&nbsp;注&nbsp;&nbsp;册&nbsp;&nbsp;</a>
            </span>
        </div>

        <div class="login_header" style="line-height: 4rem;text-align: center">
            <span style="color: orangered;font-size: 0.8rem;text-align: center">欢&nbsp;迎&nbsp;登&nbsp;录</span>
        </div>
        <br>  <br>
         <br>
        {#        注册页面#}
        <div class="login">

            <form action="{% url 'lang:judge_login' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="name">姓名</label>
                    <input type="text" name="username" class="form-control input-lg" id="name" placeholder="请输入姓名">
                </div>
              <br>
                <div class="form-group">
                    <label for="password">密码</label>
                    <input type="password" name="password" class="form-control input-lg" id="password" placeholder="请输入六位数密码">
                    <br>
                    <span style="color: red;">{{ info }}</span>
                </div>
                <br>
                <br>
                  <br>
                <button type="submit" class="btn btn-default center-block btn-lg">&nbsp;&nbsp;登&nbsp;&nbsp;&nbsp;录&nbsp;&nbsp;</button>
            </form>

        </div>
    </div>


{% endblock %}

电商项目/Lang/templates/user/register.html
{% extends 'base.html' %}
{% load static %}


{% block ext_css %}
    <link rel="stylesheet" href="{% static 'lang/register_login/css/register.css' %}">
{% endblock %}

{% block ext_js %}
    <script type="text/javascript" src="{% static 'lang/register_login/js/register.js' %}"></script>
{% endblock %}

{% block content %}

    <div class="box">

        {#        注册头部#}
        <div class="register_header" style="line-height: 4rem;text-align: center">
            <span style="color: orangered;font-size: 0.8rem">欢&nbsp;迎&nbsp;注&nbsp;册</span>
        </div>
        <br>
        {#        注册页面#}
        <div class="register">

            <form method="post" action="{% url 'lang:register' %}"  enctype="multipart/form-data" onsubmit="return check()">
                {% csrf_token %}
                <div class="form-group">
                    <label for="name">姓名</label>
                    <input type="text" name="username" class="form-control input-lg" id="name" placeholder="请输入姓名">

                    <span id="is_used"></span>

                </div>
                <div class="form-group">
                    <label for="email">邮箱</label>
                    <input type="password" name="useremail" class="form-control input-lg" id="email"
                           placeholder="请输入邮箱">
                    <span id="email_is_used"></span>
                </div>
                <div class="form-group">
                    <label for="password">密码</label>
                    <input type="password" name="userpassword" class="form-control input-lg" id="password"
                           placeholder="请输入六位数密码">
                    <span id="password_is_six"></span>

                </div>
                <div class="form-group">
                    <label for="passwordagain">密码</label>
                    <input type="password" class="form-control input-lg" id="passwordagain" placeholder="请再次输入密码">
                    <span id="passwordagain_is_same"></span>

                </div>
                <br>

                <button   id="submit_able" type="submit" class="btn btn-default center-block btn-lg">&nbsp;&nbsp;注&nbsp;&nbsp;&nbsp;册&nbsp;&nbsp;</button>
            </form>

        </div>
    </div>


{% endblock %}

电商项目/Lang/templates/user/search.html
{% extends 'base_main.html' %}

{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'lang/search/css/search.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}

    <script type="text/javascript" src="{% static 'lang/search/js/search.js' %}"></script>
{% endblock %}


{% block header %}
    {{ block.super }}
    <header>
        <div style="display: inline;line-height: 0.4rem;width: 20%;top: 0.4rem;margin: auto;color: orangered;font-size: large">
            {#            <img src="{% static 'img/1.png' %}">#}

            Welcome!<br>

        </div>
        <form method="post" action="{% url 'lang:search' %}">
            {% csrf_token %}
            <div class="row">
                <div style="top: 0.4rem;display: flex"
                     class="input-group col-xs-11 col-md-11 col-md-offset-0 col-xs-offset-0">
                    <input type="text" name="goods_info" id="goods_info" class="form-control" placeholder="搜索"
                           aria-describedby="basic-addon2">
                    <input type="submit" style="width: 1.2rem" class="input-group-addon" id="basic-addon2" value="提交">
                </div>
            </div>
        </form>

    </header>
{% endblock %}



{% block content %}
    <div style="height: 1.5rem;width: 100%;background-color: yellowgreen"></div>

    <div id="box">
        <div id="header" style=";text-align: center">

            <span style="margin: 0 auto;line-height: 1rem;font-size: larger;">
                &nbsp;&nbsp;综&nbsp;&nbsp;&nbsp;合&nbsp;&nbsp;&nbsp;排&nbsp;&nbsp;&nbsp;序&nbsp;&nbsp;
            </span>
        </div>


        <div id="content">
        <hr>
            <section>
                <menu>
                    <ul>
                        {% for goods_list in goods_lists %}
                            <li>
                                <a href="#">
                                    <img src="{{ goods_list.productimg }}">
                                    <div class="shoppingInfo">
                                        <h6>{{ goods_list.productlongname }}</h6>
                                        <p class="detailTag">
                                            <span>精选</span>
                                            <span></span>
                                        </p>
                                        <p class="unit">{{ goods_list.specifics }}</p>
                                        <p class="price">
                                            <span>{{ goods_list.price }}</span>
                                            <s>{{ goods_list.marketprice }}</s>
                                        </p>
                                    </div>
                                </a>

                                <section>
                                    <button only_id="{{ goods_list.id }}" class="sub_from_cart">－</button>
                                    <span>0</span>
                                    {#                                    通过属性来获取到该商品的信息，然后将该商品的信息传给js中#}
                                    <button only_id="{{ goods_list.id }}" class="add_to_cart">＋</button>
                                </section>
                            </li>

                        {% endfor %}
                        <div style="height: 3rem;width: 100%;"></div>

                    </ul>
                </menu>
            </section>
        </div>

    </div>







{% endblock %}