电商项目/Lang/Lang/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lang/',include('myapp.urls',namespace='lang'))
]

电商项目/Lang/myapp/urls.py
from django.contrib import admin
from django.conf.urls import url

from . import views

app_name='myapp'

urlpatterns = [
    url('^index/', views.index ,name='index'),
    # 四个基础的展示页
    url('^home/', views.home, name='home'),
    url('^market/', views.market, name='market'),
    url('^cart/', views.cart, name='cart'),
    url('^mine/', views.mine, name='mine'),

    # 对右侧数据通过标签页进行更改
    url('^changeMenu/(?P<typeid>\d+)/', views.changeMenu,name='changeMenu'),

    # 登陆注册页面
    url('^register/', views.register, name='register'),
    url('^login/', views.login, name='login'),

    # 注册信息进行判断
    url('^judge_name/', views.judge_name, name='judge_name'),
    url('^judge_email/', views.judge_email, name='judge_email'),

    # 对登录信息进行判断
    url('^judge_login/', views.judge_login, name='judge_login'),

    # mine中进行退出
    url('^sign_out/', views.sign_out, name='sign_out'),

    # 搜索物品
    url('^search/', views.search, name='search'),

    # 将market中的物品添加到购物车和减操作
    url('^add_to_cart/', views.add_to_cart, name='add_to_cart'),
    url('^sub_from_cart/', views.sub_from_cart, name='sub_from_cart'),

    # 对小球进行判断

    url('^judge_ball/', views.judge_ball, name='judge_ball'),

    # 点击下单按钮进行下单
    url('^place_an_order/', views.place_an_order, name='place_an_order'),

    # 进行订单商品的展示
    url('^show_order/', views.show_order, name='show_order'),

]

电商项目/Lang/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>{{ title }}</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/swiper.css' %}">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">

    {% block ext_css %}

    {% endblock %}

</head>
<body>

    {% block header %}

    {% endblock %}

    {% block content %}

    {% endblock %}

    {% block footer %}

    {% endblock %}

    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/base.js' %}"></script>

    {% block ext_js %}

    {% endblock %}
</body>
</html>

电商项目/Lang/templates/base_main.html
{% extends 'base.html' %}
{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'lang/main/css/main.css' %}">
{% endblock %}

{#{% block header %}#}
{#    <header></header>#}
{#{% endblock %}#}

{% block footer %}
    <footer>
        <a href="{% url 'lang:home' %}" class="home">
            <dl>
                <dt>
                    <span></span>
                </dt>
                <dd>首页</dd>
            </dl>
        </a>
        <a href="{% url 'lang:market' %}" class="market">
            <dl>
                <dt>
                    <span></span>
                </dt>
                <dd>闪购</dd>
            </dl>
        </a>
        <a href="{% url 'lang:cart' %}" class="cart">
            <dl>
                <dt>
                    <span></span>
                </dt>
                <dd>购物车</dd>
            </dl>
        </a>
        <a href="{% url 'lang:mine' %}" class="mine_icon">
            <dl>
                <dt>
                    <span></span>
                </dt>
                <dd>我的</dd>
            </dl>
        </a>
    </footer>
{% endblock %}