电商项目/Lang/Lang/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lang/',include('myapp.urls',namespace='lang'))
]

电商项目/Lang/myapp/urls.py
from django.contrib import admin
from django.conf.urls import url

from . import views

app_name='myapp'

urlpatterns = [
    url('^index/', views.index ,name='index'),
    # 四个基础的展示页
    url('^home/', views.home, name='home'),
    url('^market/', views.market, name='market'),
    url('^cart/', views.cart, name='cart'),
    url('^mine/', views.mine, name='mine'),

    # 对右侧数据通过标签页进行更改
    url('^changeMenu/(?P<typeid>\d+)/', views.changeMenu,name='changeMenu'),

    # 登陆注册页面
    url('^register/', views.register, name='register'),
    url('^login/', views.login, name='login'),

    # 注册信息进行判断
    url('^judge_name/', views.judge_name, name='judge_name'),
    url('^judge_email/', views.judge_email, name='judge_email'),

    # 对登录信息进行判断
    url('^judge_login/', views.judge_login, name='judge_login'),

    # mine中进行退出
    url('^sign_out/', views.sign_out, name='sign_out'),

    # 搜索物品
    url('^search/', views.search, name='search'),

    # 将market中的物品添加到购物车和减操作
    url('^add_to_cart/', views.add_to_cart, name='add_to_cart'),
    url('^sub_from_cart/', views.sub_from_cart, name='sub_from_cart'),

    # 对小球进行判断

    url('^judge_ball/', views.judge_ball, name='judge_ball'),

    # 点击下单按钮进行下单
    url('^place_an_order/', views.place_an_order, name='place_an_order'),

    # 进行订单商品的展示
    url('^show_order/', views.show_order, name='show_order'),

]

电商项目/Lang/templates/main/cart.html
{% extends 'base_main.html' %}

{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'lang/main/css/cart.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'lang/main/js/cart.js' %}"></script>
{% endblock %}

{% block header %}
    {{ block.super }}
    <header style="height: 2rem">
        <div style="margin: 0 auto;text-align: center">
           <span style="line-height: 2rem;color: orangered;font-size: 0.8rem;text-shadow:0.2rem 0.2rem 0.1rem lightgray;">
               购&nbsp;&nbsp;&nbsp;&nbsp;物&nbsp;&nbsp;&nbsp;&nbsp;车
           </span>
        </div>

    </header>
{% endblock %}


{% block content %}
    <div style="height: 2.1rem;width: 10rem"></div>



    {#对号小球#}
    {#    <div class="bool"><strong>√</strong></div>#}
    <div id="cart_box">

        <section>

            <menu>
                <ul>
                    {% for cart in carts %}
                        {% ifnotequal cart.goods_num 0 %}
                        <li>
                            <a href="#">
                                <img src="{{ cart.goods.productimg }}">
                                <div class="shoppingInfo">
                                    <h6>{{ cart.goods.productlongname }}</h6>
                                    <p class="detailTag">
                                        <span>精选</span>
                                        <span></span>
                                    </p>
                                    <p class="unit">{{ cart.goods.specifics }}</p>
                                    <p class="price">
                                        <span>{{ cart.goods.price }}</span>
                                        <s>{{ cart.goods.marketprice }}</s>
                                    </p>
                                </div>
                            </a>

                            <section>
                                <button only_id="{{ cart.goods.id }}" class="sub_from_cart">－</button>
                                <span>{{ cart.goods_num }}</span>
                                {#                                    通过属性来获取到该商品的信息，然后将该商品的信息传给js中#}
                                <button only_id="{{ cart.goods.id }}" class="add_to_cart">＋</button>

{#                                是否选择的小括号#}
                                {% ifequal cart.is_select 1 %}
                                <div  style="height: 0.8rem;width: 0.8rem;float: right">
                                    <div class="bool1" cart_id="{{ cart.id }}" style="float: right"><strong>√</strong></div>

                                </div>
                                {% else %}
                                     <div  style="height: 0.8rem;width: 0.8rem;float: right">
                                    <div class="bool1" cart_id="{{ cart.id }}" style="float: right;background-color: white"><strong></strong></div>

                                </div>
                                {% endifequal %}
                            </section>

                        </li>
                    {% endifnotequal %}
                    {% endfor %}
                    <div style="height: 3rem;width: 100%;"></div>

                </ul>
            </menu>
        </section>

    </div>



    <div id="top_footer" style="display: flex">
        <div style="height: 1.5rem;width: 1.5rem;">
            <div id="all_select" class="bool center-block" style="margin: 0.3rem 0;float: right"><strong>√</strong></div>
        </div>
        <div style="height: 1.5rem;width: 1.5rem;line-height: 1.5rem">
            <p style="font-size: larger;color: gray">&nbsp;&nbsp;全&nbsp;&nbsp;选</p>
        </div>
        <div style="height: 1.5rem;width: 4rem;">
            <span style="line-height: 1.5rem;font-size: larger;color: gray;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;合计：</span>
            <span id="total">{{ price }}</span>
        </div>
        <div id="place_an_order" style="height: 1.5rem;width: 3rem;background-color: orangered;line-height: 1.5rem;font-size: larger;color: gray;text-align: center;color: white">
            去&nbsp;结&nbsp;算
        </div>
    </div>
{% endblock %}

电商项目/Lang/templates/main/home.html
{% extends 'base_main.html' %}

{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'lang/main/css/home.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/swiper.jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'lang/main/js/home.js' %}"></script>
{% endblock %}


{% block header %}
    {{ block.super }}
    <header>
        <div style="display: inline;line-height: 0.4rem;width: 20%;top: 0.4rem;margin: auto;color: orangered;font-size: large">
            {#            <img src="{% static 'img/1.png' %}">#}

            Welcome!<br>

        </div>
        <form method="post" action="{% url 'lang:search' %}">
            {% csrf_token %}
            <div class="row">
                <div style="top: 0.4rem;display: flex" class="input-group col-xs-11 col-md-11 col-md-offset-0 col-xs-offset-0">
                    <input type="text" name="goods_info" id="goods_info" class="form-control" placeholder="搜索" aria-describedby="basic-addon2">
                    <input type="submit" style="width: 1.2rem" class="input-group-addon" id="basic-addon2" value="搜索">
                </div>
            </div>
        </form>

    </header>
{% endblock %}

{% block content %}
    <div style="height: 1.5rem;width: 100%"></div>
    <div class="swiper-container" id="topSwiper">
        <div class="swiper-wrapper">
            <div class="swiper-slide">
                <img src="{% static 'img/lunbo/1.jpg' %}">
            </div>
            <div class="swiper-slide">
                <img src="{% static 'img/lunbo/2.jpg' %}">
            </div>
            <div class="swiper-slide">
                <img src="{% static 'img/lunbo/3.jpg' %}">
            </div>
            <div class="swiper-slide">
                <img src="{% static 'img/lunbo/4.jpg' %}">
            </div>
            <div class="swiper-slide">
                <img src="{% static 'img/lunbo/5.jpg' %}">
            </div>
            <div class="swiper-slide">
                <img src="{% static 'img/lunbo/6.jpg' %}">
            </div>
        </div>
        <div class="swiper-pagination"></div>
    </div>
    {#    轮播图下导航#}
    <div class="topMenu">
        <nav>
            <ul>

                <li>
                    <a href="{% url 'lang:market' %}">
                        <img src="{% static 'img/home/home_first/navsmall.jpg' %}"><br>
                        <span>商品分类</span>
                    </a>

                </li>
                <li>
                    <a href="#">
                        <img src="{% static 'img/home/home_first/huismall.jpg' %}"><br>
                        <span>大优惠</span>
                    </a>

                </li>
                <li>
                    <a href="#">
                        <img src="{% static 'img/home/home_first/mansmall.jpg' %}"><br>
                        <span>个人中心</span>
                    </a>

                </li>
                <li>
                    <a href="#">
                        <img src="{% static 'img/home/home_first/moneysmall.jpg' %}"><br>
                        <span>投资理财</span>
                    </a>

                </li>
            </ul>
        </nav>
    </div>
    {#商城头条#}
    <div class="swiper-container" id="touTiao">
        <div class="swiper-wrapper">
            <div class="swiper-slide">
                <p style="font-size: 0.05rem">&nbsp;&nbsp;好消息&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[特惠]&nbsp;&nbsp;今天购物全场满300-20满500-40</p>
            </div>
            <div class="swiper-slide">
                <p style="font-size: 0.05rem">&nbsp;&nbsp;商城头条&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[公告]&nbsp;&nbsp;华北，华中地区配送延迟</p>
            </div>
            <div class="swiper-slide">
                <p style="font-size: 0.05rem">&nbsp;&nbsp;商城头条&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[新闻]&nbsp;&nbsp;本网站今日与北京市达成战略协议</p>
            </div>
        </div>
    </div>

    {#    活动条目#}

    <div class="touTiaoMenu">
        <nav>
            <ul>

                <li>
                    <a href="#">
                        <br>
                        <span style="color: orangered">真的有鱼</span><br>
                        <span>开年福利篇</span>
                        <img src="{% static 'img/home/home_huodong/tj.png' %}">

                    </a>

                </li>
                <li>
                    <a href="#">
                        <br>
                        <span style="color: orangered">囤货过冬</span><br>
                        <span>让爱早点回家</span>
                        <img src="{% static 'img/home/home_huodong/tj1.png' %}">
                    </a>

                </li>
                <li>
                    <a href="#">
                        <br>
                        <span style="color: orangered">浪漫情人节</span><br>
                        <span>甜甜蜜蜜</span>
                        <img src="{% static 'img/home/home_huodong/tj2.png' %}">
                    </a>

                </li>
            </ul>
        </nav>
    </div>

    {#    超市便利#}

    <div style="height: 1.8rem;width: 100%;background-color: #eee;line-height: 1rem;text-align: center">
        <img style="width: 10rem" src="{% static 'img/home/home_minshop/minshaop.png' %}">
    </div>

    <div class="minShopMenu">
        <nav>
            <ul>
                <li>
                    <a href="#">
                        <br>
                        <img src="{% static 'img/home/home_minshop/activity.jpg' %}">
                        <span style="font-size: smaller">春节送礼优选</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <br>
                        <img src="{% static 'img/home/home_minshop/activity1.jpg' %}">
                        <span style="font-size: smaller">送礼超值选择</span>

                    </a>
                </li>
                <li>
                    <a href="#">
                        <br>
                        <img src="{% static 'img/home/home_minshop/activity2.jpg' %}">
                        <span style="font-size: smaller">佳节送礼必选</span>

                    </a>
                </li>
                <li>
                    <a href="#">
                        <br>
                        <img src="{% static 'img/home/home_minshop/activity3.jpg' %}">
                        <span style="font-size: smaller">走亲访友佳品</span>

                    </a>
                </li>


            </ul>
        </nav>
    </div>

    {#        商场活动#}

    <div style="height: 1rem;width: 10rem;background-color: lightgray;line-height: 1rem;text-align: center;">
        <p style="font-size: larger"><strong>活&nbsp;&nbsp;动</strong></p>
    </div>




    <!--首页主显示-->
    <ul>
        {% for main_show in main_shows %}
            <li class="mainInfo">
                <section>
                    <h3>
                        {{ main_show.name }}
                        <a href="#">
                            更多>>
                            <span></span>
                        </a>
                    </h3>
                    <div>
                        <a href="#">
                            <img src="{{ main_show.img }}" alt="{{ main_show.name }}">
                        </a>
                    </div>
                    <ul>
                        <li>
                            <a href="#">
                                <img src="{{ main_show.img1 }}" alt="{{ main_show.longname1 }}">
                                <div class="description">{{ main_show.longname1 }}</div>
                                <span>{{ main_show.price1 }}</span>
                                <s>{{ main_show.marketprice1 }}</s>
                            </a>
                            <button>
                                <span>+</span>
                            </button>
                        </li>
                        <li>
                            <a href="#">
                                <img src="{{ main_show.img2 }}" alt="{{ main_show.longname2 }}">
                                <div class="description">{{ main_show.longname2 }}</div>
                                <span>{{ main_show.price2 }}</span>
                                <s>{{ main_show.marketprice2 }}</s>
                            </a>
                            <button>
                                <span>+</span>
                            </button>
                        </li>
                        <li>
                            <a href="#">
                                <img src="{{ main_show.img2 }}" alt="{{ main_show.longname2 }}">
                                <div class="description">{{ main_show.longname2 }}</div>
                                <span>{{ main_show.price2 }}</span>
                                <s>{{ main_show.marketprice2 }}</s>
                            </a>
                            <button>
                                <span>+</span>
                            </button>
                        </li>
                    </ul>
                </section>

            </li>
        {% endfor %}
    </ul>
    <div style="height: 1rem;width: 10rem;background-color: white"></div>
{% endblock %}

电商项目/Lang/templates/main/market.html
{% extends 'base_main.html' %}
{% load static %}

{% block header %}
    {{ block.super }}
    <header>
        <div style="display: inline;line-height: 0.4rem;width: 20%;top: 0.4rem;margin: auto;color: orangered;font-size: large">
            {#            <img src="{% static 'img/1.png' %}">#}

            Welcome!<br>

        </div>
        <form method="post" action="{% url 'lang:search' %}">
            {% csrf_token %}
            <div class="row">
                <div style="top: 0.4rem;display: flex" class="input-group col-xs-11 col-md-11 col-md-offset-0 col-xs-offset-0">
                    <input type="text" name="goods_info" id="goods_info" class="form-control" placeholder="搜索" aria-describedby="basic-addon2">
                    <input type="submit" style="width: 1.2rem" class="input-group-addon" id="basic-addon2" value="搜索">
                </div>
            </div>
        </form>

    </header>
{% endblock %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'lang/main/css/market.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'lang/main/js/market.js' %}"></script>

{% endblock %}

{% block content %}
    <div style="height: 1.5rem;width: 10rem"></div>
    <div style="height: 1rem;width: 10rem;background-color: lightgray;line-height: 1rem;">
        <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;全部分类</span>
        <span class="backHome" style="float: right">返回&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
    </div>
    <div id="box">
        {#    左侧导航栏#}
        <div id="left">

            <ul class="nav nav-stacked">
                {% for food_type in food_types %}
                    <li role="presentation"><a href="{% url 'lang:changeMenu' typeid=food_type.typeid %}">{{ food_type.typename }}</a></li>
                {% endfor %}
            </ul>

        </div>
        {#右侧导航栏#}
        <div id="right">

            <section>
                <menu>
                    <ul>
                        {% for goods_list in goods_lists %}
                            <li>
                                <a href="#">
                                    <img src="{{ goods_list.productimg }}">
                                    <div class="shoppingInfo">
                                        <h6>{{ goods_list.productlongname }}</h6>
                                        <p class="detailTag">
                                            <span>精选</span>
                                            <span></span>
                                        </p>
                                        <p clas s="unit">{{ goods_list.specifics }}</p>
                                        <p class="price">
                                            <span>{{ goods_list.price }}</span>
                                            <s>{{ goods_list.marketprice }}</s>
                                        </p>
                                    </div>
                                </a>

                                <section>
                                    <button only_id="{{ goods_list.id }}" class="sub_from_cart">－</button>
                                    <span  only_id="{{ goods_list.id }}" class="goods_num">0</span>
    {#                                通过属性来获取到该商品的信息，然后将该商品的信息传给js中#}
                                    <button only_id="{{ goods_list.id }}" class="add_to_cart">＋</button>
                                </section>
                            </li>
                        {% endfor %}

                    </ul>
                </menu>
            </section>

        </div>

    </div>
    </div>
    <div style="height: 1.5rem;width: 10rem"></div>

{% endblock %}

电商项目/Lang/templates/main/mine.html
{% extends 'base_main.html' %}

{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'lang/main/css/mine.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    {#    <script type="text/javascript" src="{% static 'js/swiper.jquery.js' %}"></script>#}
    <script type="text/javascript" src="{% static 'lang/main/js/mine.js' %}"></script>
{% endblock %}

{% block content %}


    <div class="top1">
    </div>
    <div class="m-userinfo">
        <div class="m-baseinfo">
            <a href="information.html">
                <img src="{% static 'img/mine/top/top2.jpg' %}">
            </a>
            {#                显示的是用户名#}

            {#                未登陆时用户显示的内容#}
            {% ifequal flag 1 %}
                {#登陆后用户显示的内容#}
                <em class="s-name" style="font-size: large">({{ username }})<span class="vip1"></span></em>
                <div class="s-prestige am-btn am-round">
                    会员福利
                </div>

            {% else %}
                <em class="s-name" style="font-size: large">(用户未登陆)<span class="vip1"></span></em>
                <div class="s-prestige am-btn am-round">
                    <span id="denglu">点击登录</span>
                </div>
            {% endifequal %}


        </div>
        <div class="m-right">
            <div class="m-new">
                <a href="news.html"><i class="am-icon-bell-o"></i>&nbsp;&nbsp;</a>
            </div>
            <div class="m-address">
                <a href="address.html" class="i-trigger">我的收货地址</a>
            </div>
        </div>
    </div>
    </div>

    <div class="top3">

    </div>

    <div style="height: 1rem;"></div>
    {#    红包展示#}


    <div class="money">
        <nav>
            <ul>
                <li>
                    <img style="border-radius: 50%;" src="{% static 'img/mine/money/bonus.png' %}"><br>
                    <span style="font-size: large">红包</span>

                </li>
                <li>
                    <img src="{% static 'img/mine/money/coupon.png' %}"><br>
                    <span style="font-size: large">优惠券</span>
                </li>
                <li>
                    <img src="{% static 'img/mine/money/wallet.png' %}"><br>
                    <span style="font-size: large">钱包</span>
                </li>
            </ul>
        </nav>
    </div>


    {#    我的订单#}
    <div style="height: 0.5rem;width: 100%;line-height: 1rem;">
        <span style="float: left;font-size: larger;color: darkgray">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;我的订单</span>
        <span style="float: right;color: darkgray">全部订单&nbsp;&nbsp;&nbsp;&nbsp;</span>
    </div>
    <hr style="width: 8rem;">

    <div class="order">
        <nav>
            <ul>

                <li>
                    <img src="{% static 'img/mine/order/pay.png' %}"><br>
                    <span>待付款</span>
                </li>
                <li>
                    <img src="{% static 'img/mine/order/send.png' %}"><br>
                    <span>代发货</span>
                </li>
                <li>
                    <img src="{% static 'img/mine/order/receive.png' %}"><br>
                    <span>待收货</span>
                </li>
                <li>
                    <img src="{% static 'img/mine/order/comment.png' %}"><br>
                    <span>待评价</span>
                </li>
                <li>
                    <img src="{% static 'img/mine/order/refund.png' %}"><br>
                    <span>退换货</span>
                </li>

            </ul>
        </nav>
    </div>

    {#    我的收藏#}
    <div style="height: 0.5rem;width: 100%;line-height: 1rem;">
        <span style="float: left;font-size: larger;color: darkgray">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;我的收藏</span>
        {#        <span style="float: right;color: darkgray">全部收藏&nbsp;&nbsp;&nbsp;&nbsp;</span>#}
    </div>
    <hr style="width: 8rem;">

    <div class="save">
        <nav>
            <ul>
                <li>
                    <img src="{% static 'img/mine/save/save1.jpg' %}"><br>
                    <span style="color: gray;">最爱橙子</span>
                </li>
                <li>
                    <img src="{% static 'img/mine/save/save2.jpg' %}"><br>
                    <span style="color: gray;">最爱巧克力</span></li>
                <li>
                    <img src="{% static 'img/mine/save/save3.jpg' %}"><br>
                    <span style="color: gray;">最爱威化饼</span></li>
                <li>
                    <img src="{% static 'img/mine/save/save4.jpg' %}"><br>
                    <span style="color: gray;">最爱甜点</span></li>
            </ul>
        </nav>
    </div>

    {#    经常浏览#}

    <div style="height: 0.5rem;width: 100%;line-height: 1rem;">
        <span style="float: left;font-size: larger;color: darkgray">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;经常浏览</span>
        {#        <span style="float: right;color: darkgray">全部收藏&nbsp;&nbsp;&nbsp;&nbsp;</span>#}
    </div>
    <hr style="width: 8rem;">

    <div class="history">
        <nav>
            <ul>
                <li>
                    <img src="{% static 'img/mine/histoty/histoty1.jpg' %}"><br>
                    <span style="color: gray;">护肤常用</span>
                </li>
                <li>
                    <img src="{% static 'img/mine/histoty/histoty2.jpg' %}"><br>
                    <span style="color: gray;">家中必备</span></li>
                <li>
                    <img src="{% static 'img/mine/histoty/histoty3.jpg' %}"><br>
                    <span style="color: gray;">零食小吃</span></li>
                {#                <li>#}
                {#                    <img src="{% static 'img/mine/histoty/histoty4.jpg' %}"><br>#}
                {#                    <span style="color: gray;">最爱甜点</span></li>#}
            </ul>
        </nav>
    </div>

    {#    点击退出#}

    <div class="m-userinfo" style="background-color: white">
        <div class="m-baseinfo">
            <div class="s-prestige am-btn am-round center-block" style="height: 1rem;width: 4rem;line-height: 1rem">
                <span id="sign_out" style="font-size: larger;color: orangered">退出登陆</span>
            </div>
        </div>
    </div>
    </div>



    <div style="height: 2rem;width: 10rem;"></div>
{% endblock %}